name: Audit

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"

    - name: Setup pnpm
      uses: pnpm/action-setup@v3

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Compile Extension
      run: pnpm compile

    - name: Test Extension
      run: pnpm test
