name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"

    - name: Setup pnpm
      uses: pnpm/action-setup@v3

    - name: Install VSCode Extension Manager
      run: pnpm install --global vsce

    - name: Install Open VSX Extension Manager
      run: pnpm install --global ovsx

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Extension
      run: pnpm build

    - name: Package Extension
      run: vsce package --no-dependencies

    - name: Release Extension on VSCode Marketplace
      env:
        VSCE_PAT: ${{secrets.VSCE_RELEASE_TOKEN}}
      run: vsce publish --no-dependencies

    - name: Release Extension on Open VSX
      env:
        OVSX_PAT: ${{secrets.OVSX_RELEASE_TOKEN}}
      run: ovsx publish --no-dependencies

    - name: Release Extension on GitHub
      env:
        GH_TOKEN: ${{github.token}}
      run: |
        v=$(jq --raw-output ".version" package.json)
        gh release create "v${v}" --generate-notes
        gh release upload "v${v}" *.vsix
